### ISSUE TITLE
Using arrayUnion with References does not work

### ISSUE THREAD

**Issue by nxcco** [atn832/cloud_firestore_mocks#109]
When I executed this code:
```dart
mockFirestoreInstance.document('users/user').updateData({
'references': FieldValue.arrayUnion([MockDocumentReference]), // doesn't matter which reference
});
```
then there is always added **null** to the array (here called _references_).

Any idea what causes this bug?

**Comment by sensuikan1973** [comment]
dup https://github.com/atn832/cloud_firestore_mocks/issues/106
