### ISSUE TITLE
Support `FieldValue.serverTimestamp()`

### ISSUE THREAD

**Issue by atn832** [atn832/cloud_firestore_mocks#12]
The cloud_firestore example uses this extensively: [main.dart](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/lib/main.dart).

**Comment by suztomo** [comment]
I'm going to create a PR for this. I'm feeling just replacing DateTime.now() works fine.

**Comment by atn832** [comment]
Thank you for your contribution. I'll release an update this weekend!
