### ISSUE TITLE
Add support for cloud_firestore 0.14.0+

### ISSUE THREAD

**Issue by zeshuaro** [atn832/cloud_firestore_mocks#125]
`cloud_firestore` 0.14.0 introduced a lot of breaking changes, can `cloud_firestore_mocks` be updated to work with the latest firestore plugin?

**Comment by sensuikan1973** [comment]
I make Draft PR on my repo https://github.com/sensuikan1973/cloud_firestore_mocks/pull/4.
After https://github.com/atn832/cloud_firestore_mocks/pull/126 has merged, I send the PR.

**Comment by atn832** [comment]
Looks like a lot of work. Thank you @sensuikan1973 for taking the time to do it!

**Comment by eliseyOzerov** [comment]
Any updates on the merge? I'v updated my codebase to support cloud_firestore 0.14.0 before i found this plugin and now i can't test it ~..~

**Comment by zeshuaro** [comment]
> Any updates on the merge? I'v updated my codebase to support cloud_firestore 0.14.0 before i found this plugin and now i can't test it ~..~

You can use the updated branch until it's merged https://github.com/sensuikan1973/cloud_firestore_mocks/tree/support_cloud_firesote_0.14.0

**Comment by eliseyOzerov** [comment]
> > Any updates on the merge? I'v updated my codebase to support cloud_firestore 0.14.0 before i found this plugin and now i can't test it ~..~
> 
> You can use the updated branch until it's merged https://github.com/sensuikan1973/cloud_firestore_mocks/tree/support_cloud_firesote_0.14.0

oh, thank you 👍

**Comment by sensuikan1973** [comment]
@eliseyOzerov 
probably,  you miss branch specification `support_cloud_firesote_0.14.0`

**Comment by eliseyOzerov** [comment]
@sensuikan1973 alright, this seems to have done the trick, thank you!

**Comment by atn832** [comment]
Just published your PR at https://pub.dev/packages/cloud_firestore_mocks/changelog#050. Thank you!!
