### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by AndreaCostanzo1** [atn832/cloud_firestore_mocks#129]
Good afternoon,
I'm facing an issue every time I try to run a transaction of any kind because I receive the following error (notice: using "normal" firebase, transactions work without problem):

```
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Future<Null>?'

package:cloud_firestore_mocks/src/cloud_firestore_mocks_base.dart 88:5  MockFirestoreInstance.runTransaction
```

By diving a little bit deeper in the changes of the most recent version I noticed this change:

```dart
//old version
  Future<Map<String, dynamic>> runTransaction(
      TransactionHandler transactionHandler,
      {Duration timeout = const Duration(seconds: 5)}) async {

//new version
  Future<T> runTransaction<T>(TransactionHandler<T> transactionHandler,
      {Duration timeout = const Duration(seconds: 30)}) async {

```
When I saw this change I tried to specify the transaction type (see below) to see if the issue got solved. However, even if the error disappears, the transaction is not executed.

```dart
//specify dynamic
FirebaseFirestore.instance.runTransaction<dynamic>(/*code*/);
```
So I'm guessing if the issue is related to the latest update of the package

**Comment by sensuikan1973** [comment]
The related diff of official plugin is https://github.com/FirebaseExtended/flutterfire/commit/27d574e620c3a95792682397b12e54e40abe572f#diff-4b03d320cd06661a52dd22772cf78abfL82-R181

Would you provide sample code ?
If you can, please provide test case like this **https://github.com/atn832/cloud_firestore_mocks/blob/66b043f566cd858db9670e8bc4e228fc2a167580/test/cloud_firestore_mocks_test.dart#L842**

**Comment by AndreaCostanzo1** [comment]
I tried different cases and I found that the error happens only if there isn't a return statement or you return null, while, on the official firebase plugin, even if the return statement is suggested is not mandatory.

```dart
//Sample generating the issue
final FirebaseFirestore firestoreMock = MockFirestoreInstance();

  final String mockID= 'anduqw098eh12nesad2';
  final Map<String, dynamic> mockUser = {
    'id': mockID,
    'nickname': 'nick',
    'email': 'not@relevant.com',
  };

  test('transaction get and update', () async {
    //GIVEN: SETUP DB ADDING A MOCK USER
    DocumentReference mockUserReference=firestoreMock.collection('users').doc(mockID);
    mockUserReference.set(mockUser);

    //WHEN: RUN TRANSACTION (READ+UPDATE)
    //ADD 'aaaa' to the nickname
    await firestoreMock.runTransaction((transaction) async {
      DocumentSnapshot snapshot = await transaction.get(mockUserReference);
      transaction.update(mockUserReference, {'nickname': snapshot.data()['nickname']+'aaaaa'});
      //add return here to solve.
    });

    //ASSERT:
    DocumentSnapshot userSnap = await mockUserReference.get();
    expect(userSnap.data()['nickname'], 'nickaaaa');
  });
```

**Comment by sensuikan1973** [comment]
@AndreaCostanzo1 thanks for your good report.

Because I found the reason, I will send the PR to resolve that issue.

**Comment by sensuikan1973** [comment]
https://github.com/atn832/cloud_firestore_mocks/pull/130

**Comment by atn832** [comment]
I've published @sensuikan1973's fix at https://pub.dev/packages/cloud_firestore_mocks/changelog#0501. Thank you!
