### ISSUE TITLE
Error When Initializing MockFirestoreInstance

### ISSUE THREAD

**Issue by godfreycomputing** [atn832/cloud_firestore_mocks#131]
The getter 'firestore_interface' isn't defined for the class 'MockFirestoreInstance'.

This happeneds when initializing MockFirestoreInstance in a variable.  Doesn't even try to run any tests.

**Comment by atn832** [comment]
Would you mind sharing the code that you used?

**Comment by godfreycomputing** [comment]
void main() {
      MockNetworkInfo mockNetworkInfo;
      FirestoreServiceCategory firestoreServiceCategory;
      MockFirestoreInstance mockFirestoreInstance;

      setUp(() {
        mockNetworkInfo = MockNetworkInfo();
        firestoreServiceCategory = FirestoreServiceCategory(
        networkInfo: mockNetworkInfo,
        service: mockFirestoreInstance,
        );
      });

    group('GetCategory', () {

    setUp(() {
      mockFirestoreInstance = MockFirestoreInstance();
    });

    test('Should return a single Category', () async {
      
      //act
      final result = await firestoreServiceCategory.getCategory(categoryParams);
      //assert
      expect(result, categoryModel);
    });

**Comment by atn832** [comment]
Your code is a bit strange because on line 8, you initialize firestoreServiceCategory before having initialized mockFirestoreInstance. So your firestoreServiceCategory will store a null reference for FirestoreInstance. Can you double check your code? Perhaps you want something like this:

```dart
  setUp(() {
    mockNetworkInfo = MockNetworkInfo();
    mockFirestoreInstance = MockFirestoreInstance();
    firestoreServiceCategory = FirestoreServiceCategory(
    networkInfo: mockNetworkInfo,
    service: mockFirestoreInstance,
    );
  });
```
