### ISSUE TITLE
collectionGroup doesn't work

### ISSUE THREAD

**Issue by AlexKel** [atn832/cloud_firestore_mocks#132]
Hello, 

Thanks for the great work on the library, really useful!

I've found one issue that took a while to pinpoint. We have a `collectionGroup` that contains only subcollections in the firebase. Our structure is as follows: `categories > category_id > items > item_id`. So after we mock our data and widget loads data by calling `collectionGroup('items')` it was throwing an error `entries was called on null`.
After some digging, I pinpoint the issue to the fact that `node` object was null in such a case (in the library). I then modified your test to match our use case for collection groups and got the same error.

```dart
      final firestore = MockFirestoreInstance();
      await firestore.doc('foo/foo_1/bar/bar_1').set({'value': '1'});
      await firestore.doc('foo/foo_2/bar/bar_2').set({'value': '2'});
      final querySnapshot = await firestore.collectionGroup('bar').get();
      expect(querySnapshot.docs, hasLength(2));
      expect(querySnapshot.docs.first.id, 'bar_1');
      expect(querySnapshot.docs.first.reference.path, 'foo/foo_1/bar/bar_1');
      expect(querySnapshot.docs.first.data(), {'value': '1'});
      expect(querySnapshot.docs[1].data(), {'value': '2'});
```

I didn't have much time yet to figure out why the `node` object is `null` in the first place.

If you need any more info please let me know.

**Comment by rhisiart-cufflink** [comment]
@AlexKel Did you figure it out as I'm having the same problem :-(

**Comment by rhisiart-cufflink** [comment]
@AlexKel You can try this PR using the following in your `pubspec.yaml`:

```
  cloud_firestore_mocks:
    git:
      url: https://github.com/atn832/cloud_firestore_mocks.git
      ref: df52093c132dfb27958e4a38dd1fd0b9a6ca7b71
```

**Comment by atn832** [comment]
I just published your PR at https://pub.dev/packages/cloud_firestore_mocks/changelog#052. Please use version 0.5.2 to get the fix.

Thanks for contributing the PR @rhisiart-cufflink and thanks @AlexKel for reporting the issue!
