### ISSUE TITLE
Where query doesn't work in nested objects

### ISSUE THREAD

**Issue by dfourcfive** [atn832/cloud_firestore_mocks#137]
Hello guys first thank you for this package 
so basically i'm trying to get documents where a field in a field should be equal to something 
it doesn't throw any kind of error so instead it print nothing 
here's my demo code:

```
  final snapshot = await instance.collection('users');
await snapshot
      .where('address.country', isEqualTo: 'Canada')
      .get()
      .then((value) {
    if (value != null) {
           value.docs.forEach((element) {
        print(element.data());
      });
    } else {
      //this doesn't happen at all :)
      print('its null');
    }
  });
```

**Comment by atn832** [comment]
This is now supported as of version 0.8.2. See https://pub.dev/packages/cloud_firestore_mocks/changelog#082.
