### ISSUE TITLE
Make cloud_firestore_mocks soundly null-safe

### ISSUE THREAD

**Issue by atn832** [atn832/cloud_firestore_mocks#149]
With #145, we migrated to null-safety, but to be soundly null-safe, we have to change the way we use Mockito. Instead of extending Mock, we should use annotations to generate mocks as per https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md.

**Comment by SSebigo** [comment]
Why didn't you just go with [Mocktail](https://pub.dev/packages/mocktail) ? basically Mockito w/o the annotations and generations, it's by Felix Angelov the creator of flutter_bloc

**Comment by atn832** [comment]
Resolved by fixing #33, and published at https://pub.dev/packages/cloud_firestore_mocks/changelog#083.
