### ISSUE TITLE
`size` property is null when querying a collection

### ISSUE THREAD

**Issue by zakton5** [atn832/cloud_firestore_mocks#159]
```
final messagesSnap = await mockFirestore.collection('messages').get();
expect(messagesSnap.size, 1);
```

Fails with
```
Expected: <1>
  Actual: <null>
```

`messagesSnap.docs` is populated with the single object I expect. So a workaround is `expect(messagesSnap.docs.length, 1)`

**Comment by ilkkanisula** [comment]
I noticed same issue with my tests. Thanks for the workaround tip.

**Comment by atn832** [comment]
Thanks for reporting the issue. I fixed it at https://github.com/atn832/cloud_firestore_mocks/commit/4d8a27c763a423a9a830db91d6c36b0d763334c9 and released it at https://pub.dev/packages/cloud_firestore_mocks/changelog#083.
