### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by idkq** [atn832/cloud_firestore_mocks#161]
Docs instead of documents. data() etc

```dart
print(snapshot.docs.length); // 1
    print(snapshot.docs.first.data()['name']); // 'Bob'
    print(instance.dump());
```

**Comment by atn832** [comment]
Thanks for reporting. I just updated the README at https://github.com/atn832/cloud_firestore_mocks/commit/f18012052f9286576f71332ae99444d72c8c86ad and published an update.
