### ISSUE TITLE
Idea: a way to run cloud_firestore_mocks_test.dart with real Firestore

### ISSUE THREAD

**Issue by suztomo** [atn832/cloud_firestore_mocks#17]
I wish there is a way to run the test with real Firestore instance. With such setup, contributors of this repository feel confident that cloud_firestore_mocks follows the behavior of the real implementation.

**Comment by suztomo** [comment]
Firebase Emulator? https://firebase.google.com/docs/rules/emulator-setup.

Using the emulator to develop cloud_firestore_mocks. The cloud_firestore_mocks users can benefit from easy Firestore unit tests (without setting up the emulator).

**Comment by suztomo** [comment]
Integration Test with contributor's dummy Firebase project (no security)

## Test Structure
- test/cloud_firestore_mocks_test.dart defines `CloudFirestoreMockTests` class to run the existing widget tests. The main function calls the class, supplying MockFirestore. The widget tests cannot use "dart:ui" library ("dart:ui" is unavailable in driver test https://github.com/flutter/flutter/issues/27826).
- test_driver/app_test.dart calls the `CloudFirestoreMockTests` class, supplying real Firestore.

... But it's natural to think that the driver app does not have Firestore classes either.

## Instruction
- Create a dummy Firebase project
- Set development rules (no security)
- Place GoogleService-Info.plist to Runners/Runners via Xcode.
- Run `flutter drive --target=test_driver/app.dart`

My memo: https://gist.github.com/suztomo/eb37e00a0d0d8f364245e775d7af2861

**Comment by suztomo** [comment]
# Integration test for test app that calls CloudFirestoreMockTests with a dummy (real) firebase project

Can test-driver/app.dart call CloudFirestoreMockTests from runApp?

**Comment by atn832** [comment]
What about these integration tests? They seem to be doing what you are trying to do. Why do they not fail as well?
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore/example/test_driver

Did you get a chance to try with the Emulator that you mentioned? It would make it cleaner since we wouldn't  need to create an actual account and a test database.

**Comment by suztomo** [comment]
Thank for the reference for the integration test. It should work as long ad test code is in app side, not driver code. I will give it a try.


Emulator method didn’t work for me. 
I followed https://firebase.google.com/docs/emulator-suite/connect_and_prototype
Firestore’s “setting” method (to specify localhost) never returned.

**Comment by suztomo** [comment]
Found example directory.

```
suztomo@Tomohiros-MBP.verizon.net ~/Documents/cloud_firestore_mocks/example
~/Documents/cloud_firestore_mocks/example $ flutter drive --target=test_driver/cloud_firestore.dart

Using device iPhone 11 Pro Max.
Starting application: test_driver/cloud_firestore.dart
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before
submitting to the App Store.
 
Running pod install...                    
```
