### ISSUE TITLE
Run tests automatically on new PRs

### ISSUE THREAD

**Issue by atn832** [atn832/cloud_firestore_mocks#19]
and perhaps show that they pass on the master branch too.

**Comment by suztomo** [comment]
https://github.com/atn832/cloud_firestore_mocks/pull/39#pullrequestreview-374891408

> I wonder if eventually, it would be possible to run the full battery of unit tests from cloud_firestore_mocks/test/* on the mock library and emulator/real firebase as part of #19.

Nice idea. The challenge is resetting the state of emulator and real firebase. For cloud_firestore_mocks, reseting its state is easy; just creating a MockFirestore instance. For emulator and real firebase, I don't know how to reset their state (collection and documents) via Dart.

**Comment by atn832** [comment]
Reference docs:

* https://flutter.dev/docs/deployment/cd#other-services
* https://github.com/marketplace/actions/flutter-action
