### ISSUE TITLE
Document and write tests for Firestore.batch

### ISSUE THREAD

**Issue by suztomo** [atn832/cloud_firestore_mocks#25]
(I haven’t tested but I assume this is not implemented. I’m going to use batch in my Flutter app)

Similar to a transaction but a batch holds only write operations.

Example usage of batch
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/example/lib/main.dart#L110

**Comment by atn832** [comment]
It's actually supported. I use it in my projects too. But I forgot to document and write tests for it.

https://github.com/atn832/cloud_firestore_mocks/blob/9b9f5502a03656479faa4b135a7fe92f829f0e26/lib/src/cloud_firestore_mocks_base.dart#L29

**Comment by suztomo** [comment]
@atn832 Great to hear it's implemented.  Thank you.

I might contribute to this documentation and testing.

**Comment by suztomo** [comment]
Note to myself: updateData() and delete() ?
