### ISSUE TITLE
[ERROR: Bad state] Mocking response with when()

### ISSUE THREAD

**Issue by cocacrave** [atn832/cloud_firestore_mocks#26]
Trying to mock when().then() but I get an error:
`ERROR: Bad state: Mock method was not called within when(). Was a real method called?`

```
test(
      'should return user document',
      () async {
        when(mockService.collection(any).document(any)).thenAnswer(
          (_) => tUserDoc,
        );
        // expect
        // verify
      },
```

**Comment by suztomo** [comment]
(I'm not author of this library) This library is becoming more "fake" than "mock". To prepare database that contain some data, you need to populate it.

```
mockFirestoreInstance.collection("users").add({"name": "suztomo"});
```

@atn832 In document, you may want to clarify which parts are "fake" and what are "mock". (I believe this library is a "fake", and fake is suitable for my usage)
https://blog.pragmatists.com/test-doubles-fakes-mocks-and-stubs-1a7491dfa3da

**Comment by atn832** [comment]
You're right, calling the library `mocks` is a misnomer. It was true initially since everything extended Mock and implementation was minimal. I've filed #33 and #34. I'll see if #34 is doable.

Closing this since the fix is to populate the fake db like @suztomo mentioned.
