### ISSUE TITLE
conflict with cloud_firestore plugin

### ISSUE THREAD

**Issue by terry960302** [atn832/cloud_firestore_mocks#3]
there's a version issue between cloud_firestore and cloud_firestore_mocks.
want a new version of cloud_firestore_mocks

```
Because every version of cloud_firestore_mocks depends on cloud_firestore ^0.12.9+6 and <project name> depends on cloud_firestore ^0.13.0, cloud_firestore_mocks is forbidden.
```

**Comment by atn832** [comment]
Just released an update as version 0.2.5: https://pub.dev/packages/cloud_firestore_mocks#025.

Thanks for letting me know!
