### ISSUE TITLE
Implement Query.where with whereIn

### ISSUE THREAD

**Issue by atn832** [atn832/cloud_firestore_mocks#67]
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/Query#whereIn(com.google.firebase.firestore.FieldPath,%20java.util.List%3C?%20extends%20java.lang.Object%3E)

**Comment by atn832** [comment]
This is where it should be implemented: https://github.com/atn832/cloud_firestore_mocks/blob/65a0655f0ade657957d2e00e3154775e466103df/lib/src/mock_query.dart#L89

**Comment by diegoveloper** [comment]
hi @atn832 beside from that class,  in which class should we add the tests?

**Comment by atn832** [comment]
@diegoveloper in here: https://github.com/atn832/cloud_firestore_mocks/blob/master/test/mock_query_test.dart

And also (optionally) in https://github.com/atn832/cloud_firestore_mocks/blob/master/test_driver/cloud_firestore_behaviors.dart. This is to test that our custom implementation behaves the same as the real Firebase and the Firebase emulator.

**Comment by anuragbhd** [comment]
I need this functionality in one of my apps. Opened a PR that hopefully fixes this.
