### ISSUE TITLE
Nested object support in MockQuery

### ISSUE THREAD

**Issue by C-Alexander** [atn832/cloud_firestore_mocks#81]
```
  await fs.collection("tests").add({"testSubObject": {"key": "abc"}});

var result = await fs.collection("tests").where("testSubObject.key", isEqualTo: "abc").getDocuments();

    print(result.documents.length);
```

Right now this returns 0 documents, whilst in FireStore it returns 1 document. 

This has lead to some of our code becoming impossible to test with cloud_firestore_mocks, though I am not sure how many people actually use this feature...

**Comment by r0mmen** [comment]
Any updates on this one?

**Comment by atn832** [comment]
This is now supported as of version 0.8.2. See https://pub.dev/packages/cloud_firestore_mocks/changelog#082.
